### ISSUE TITLE
background noise in multi-band melgan

### ISSUE THREAD

**Issue by xiaoyangnihao** [monatis/german-tts#2]
Hi,  in your third note,  multi-band melgan will cause some background noise, so how I can avoid the background ? What's the optimazations you mean ?

**Comment by monatis** [comment]
Hi @xiaoyangnihao! "Optimizations" refer to optimizations applied when exporting models to the TF Lite format. Default optimizations apply quantization to reduce the model size, but it leads to lower precision in model parameters and thus noisy voice synthesis. Therefore, I exported MB MelGAN without such optimizations but Tacotron2 with default optimizations.

Tl; dr: You don't need to do anything to avoid noise, and you can directly use the code in `inference_tflite.py` with `tf-nightly`installed on your system.

**Comment by xiaoyangnihao** [comment]
thx, I got it.
