### ISSUE TITLE
Several typos in inference_tflite.py code and missing audio generation 

### ISSUE THREAD

**Issue by eqikkwkp25-cyber** [monatis/german-tts#3]
diff inference_tflite.py inference_tflite_corrected.py 
89a90
>     processor = Processor()
136c137
<     mbmelgan_interpreter = tf.lite.Interpreter(model_path=path_tombmelgan[:-6] + "tflite")
---
>     mbmelgan_interpreter = tf.lite.Interpreter(model_path=path_to_melgan[:-6] + "tflite")
142c143,148
<     audio = inference_tflite("Möchtest du das meiner Frau erklären? Nein? Ich auch nicht.", interpreter, mbmelgan_interpreter)
\ Kein Zeilenumbruch am Dateiende.
---
>     start = time.time()
>     audio = infer_tflite("Möchtest du das meiner Frau erklären? Nein? Ich auch nicht.", interpreter, mbmelgan_interpreter)
> 
>     duration = time.time() - start
>     print(f"it took {duration} secs")
>     wavfile.write("sample.wav", 22050, audio)

**Comment by monatis** [comment]
I was cherrypicking this code from the e2e notebook, and a little bit lazy at midnight, hence the typos. Fixed it now, and thanks a lot for letting me know about it.
