### ISSUE TITLE
Adding "emotional" sentences to "thorsten" dataset

### ISSUE THREAD

**Issue by thorstenMueller** [monatis/german-tts#5]
Hi @monatis.
Thanks for your efforts on training models based on my free german dataset.
This is not an issue, more like an information on what i'm planning to do next on my dataset.

In mid january 2021 i'll start recording phrases in an emotional manner (https://arxiv.org/pdf/1901.04276.pdf) and publish them as usually. Because i'm not an actor or professional voice i hope to read the phrases in a normal way of emotions and not too emotional.

Next steps:
* Choose random 300 phrases (around 50 chars length each), no special emotional phrases, from existing dataset
* Record every one of these phrases in following emotions:
  * Amused (Erfreut)
  * Angry (Wütend)
  * Disgusted (Angeekelt)
  * Sleepy (Schläfrig)
  * Surprised (Überrascht)

See also:
https://discourse.mozilla.org/t/contributing-my-german-voice-for-tts/48150/217?u=mrthorstenm

Maybe that's interesting for you too.

**Comment by monatis** [comment]
Hi @thorstenMueller, thanks a lot for your contribution to the community with free and fair datasets. I find this paper interesting too, and I'm quite excited about working with such a datasets for emotional TTS. Looking forward to listening to your new recordings and giving feedback as you said on Mozilla forum. One suggestion of mine would be add recordings with the emotion "surprised."

Besides, my work will continue with the main Thorsten dataset and I aim at training a better version of Tacotron2 and a Fastspeech2 for edge deployment.
Additionally, I will provide a production-ready API implementation for use on the server side as well as a Dockerized service for use in SBCs such as RPi. Hope that these will be ready after Christmas holidays.

**Comment by thorstenMueller** [comment]
I've added "surprised" to the list in my first post. Do you think 300 phrases for each emotion are sufficient?

I'm looking forward for your SBC efforts, because this might give local TTS a huge boost 👍

**Comment by monatis** [comment]
The paper apparently used recordings of one speaker from [EmoV-DB](https://github.com/numediart/emov-db) dataset, and the number of utterences by a speaker per emotion ranges from 180 to 500. In this case, 300 utterences per emotion seems to be reasonable and balanced 🚀

**Comment by monatis** [comment]
> I'm looking forward for your SBC efforts, because this might give local TTS a huge boost 👍

Yeah my goal is provide open and free TTS and STT in German to run local on the edge (I'll go on with the STT part after I'm done with TTS). Hope that it will boost open source voice assistant efforts just like Mycroft.

**Comment by monatis** [comment]
Also linking [tacotron2-vae](https://github.com/jinhan/tacotron2-vae) and [tacotron2-gst](https://github.com/jinhan/tacotron2-gst) here for reference. I'm thinking of finetuning German Tacotron2 in a way similar to the GST method as a first attempt with your emotional dataset when you make it available @thorstenMueller 🚀

**Comment by thorstenMueller** [comment]
I've recorded one sentence in different emotions, but even i find it difficult to differ all emotions.
Maybe i have to record with more emotion in voice.

What do you think @monatis ?
https://soundcloud.com/thorsten-mueller-395984278/sets/thorsten-de-test-emotionaler

**Comment by monatis** [comment]
Hi @thorstenMueller! Yeah I agree that you better emphasize emotions more --it's just hard to differentiate between emotions to my ear with this sample. There's also such an application as to score the level of emotion expressed between 0 and 1, but this is more suitable for larger datasets like thousands of samples per emotion. Since you will record around 300 samples per emotion, I think it's better if you can exaggerate emotions little bit more :)

**Comment by thorstenMueller** [comment]
I'll record the same sentence soon and try to bring in more hearable emotions.

**Comment by thorstenMueller** [comment]
Sounds little bit creepy ;-).
It's a bad microphone, just for testing purposes. Bit more emotions lead to faster/slower recording (not same speaking pace as in my primary dataset).

https://soundcloud.com/thorsten-mueller-395984278/sets/thorsten-de-emotionale-aufnahmen-test-2

**Comment by monatis** [comment]
In fact it's natural to bring in different prosodic features with different emotions, and this is what makes emotional TTS special. Besides, since we're using guided attension most of the time, I hope it will more easily adapt to changing prosodies.
This recording sounds ok to me to convey emotions. Thanks for your great efforts in this 🚀

**Comment by thorstenMueller** [comment]
Thanks for your feedback and glad my emotional recordings might be helpful.

**Comment by monatis** [comment]
Good luck with that, and looking forward to it :-)

**Comment by eqikkwkp25-cyber** [comment]
Recordings #2 are much better than #1.

**Comment by eqikkwkp25-cyber** [comment]
> Besides, my work will continue with the main Thorsten dataset and I aim at training a better version of Tacotron2 and a Fastspeech2 for edge deployment.
> Additionally, I will provide a production-ready API implementation for use on the server side as well as a Dockerized service for use in SBCs such as RPi. Hope that these will be ready after Christmas holidays.

Hello @monatis I hope you are doing well. @thorstenMueller and i noticed that it is quiet in this repository, training takes time :-) Do you have any news?

**Comment by monatis** [comment]
hi @eqikkwkp25-cyber, I'm in the process of exiting my startup and starting with a new job, so I've been quite busy over the last three-to-four weeks. But I made a progress on that side and I'm returning to my opensource work including this one.

**Comment by thorstenMueller** [comment]
Wishing you all the best for a good start in your new job.

**Comment by thorstenMueller** [comment]
Corpus is ready, recording place is set up.
Ready to record a free german emotional dataset.

I'll document progress here: https://github.com/thorstenMueller/deep-learning-german-tts/issues/13

**Comment by monatis** [comment]
Hi @thorstenMueller It's great news that you're all set for this emotional dataset, thanks a lot for your efforts 🚀 
So I'm closing the issue in this repo and I'll follow the progress in your repo.
